# Generated by Django 5.0.6 on 2024-07-10 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_price_for_medicine_medicine_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='title',
        ),
    ]
