# Generated by Django 5.0.6 on 2024-07-10 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_medicine_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='image_for_medicine',
            new_name='image',
        ),
    ]
