# Generated by Django 5.0.6 on 2024-07-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Докторы'},
        ),
    ]
