# Generated by Django 5.0.7 on 2024-07-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
