# Generated by Django 5.0.6 on 2024-07-09 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('categories', '0002_alter_category_options_alter_category_name'),
        ('doctors', '0002_alter_doctor_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='choosing_a_disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Выбор болезни'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='choosing_a_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Выбор врача'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_of_reservation',
            field=models.DateField(verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
