# Generated by Django 5.0.6 on 2024-07-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='choosing_a_disease',
        ),
    ]
