# Generated by Django 5.0.6 on 2024-07-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_delete_day_schedule_day_schedule_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday')], max_length=12),
        ),
    ]
