# Generated by Django 5.0.6 on 2024-07-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_alter_schedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='calendar',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
